---
- name: Provisioning a new EC2 using Ansible playbook
  hosts: localhost
  connection: local
  gather_facts: False
  become: yes
  become_method: sudo
  tags: provisioning

  vars:
    key_name: new-key
    instance_type: t2.micro
    image_id: ami-0f8ca728008ff5af4
    wait: yes
    security_group: ec2-security-group
    count: 1
    region: ap-south-1

  tasks:
    - name: Create a security group
      local_action:
        module: ec2_group
        name: "{{ security_group }}"
        description: Security Group for webserver Servers
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 8080
            to_port: 8080
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
      register: basic_firewall

    - name: Launch the new EC2 Instance
      local_action:
        module: amazon.aws.ec2_instance
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ image_id }}"
        wait: "{{ wait }}"
        region: "{{ region }}"
        count: "{{ count }}"
        security_group: "{{ security_group }}"
      register: ec2
      

    - name: Add tagging to EC2 instance
      local_action: ec2_tag resource={{ item_id }} region={{ region }} state=present
      with_items: "{{ ec2.instances }}"
      args:
        tags:
          Name: MyTargetEc2Instance
