---
- name: Provisioning a new EC2 instance using Ansible
  hosts: localhost
  connection: local
  gather_facts: false
  become: yes
  become_method: sudo
  tags: provisioning

  vars:
    keypair: new-key.pem
    instance_type: t2.micro
    image_id: ami-0f8ca728008ff5af4
    wait: yes
    group: webserver
    count: 1
    region: ap-south-1
    security_group: ec2-security-group

  tasks:
    - name: Create a security group
      amazon.aws.ec2_group:
        name: "{{ security_group }}"
        description: Security Group for webserver Servers
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 8080
            to_port: 8080
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
      register: basic_firewall

    - name: Launch the new EC2 instance
      amazon.aws.ec2_instance:
        group: "{{ security_group }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ image_id }}"
        wait: "{{ wait }}"
        region: "{{ region }}"
        keypair: "{{ keypair }}"
        count: "{{ count }}"
      register: ec2

    - name: Add tagging to EC2 instance
      amazon.aws.ec2_tag:
        resource: "{{ item.id }}"
        region: "{{ region }}"
        state: present
        tags:
          Name: MyTargetEc2Instance
      with_items: "{{ ec2.instances }}"
